name: game_dev
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.32.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/images/player.png'
    - 'assets/images/player-sprite.png'
    - 'assets/images/stars.png'
    - 'assets/images/stars_0.png'
    - 'assets/images/stars_1.png'
    - 'assets/images/stars_2.png'
    - 'assets/images/explosion.png'
    - 'assets/images/enemy.png'
    - 'assets/images/bullet.png'
